runtime: ruby27
service: randomquotes-ruby
entrypoint: bundle exec rackup -s Unicorn -p $PORT

handlers:
  - url: /(.*\.(html|css|js))$
    static_files: lib/public/\1
    upload: lib/public/.*\.(html|css|js)$